#!/bin/bash

echo "Debug mode: 2 + 2"
build-debug/myCalc add 2 2

echo "Debug mode: sort 3 10 2 8 7 9 1 4 5 6"
build-debug/myCalc sort 3 10 2 8 7 9 1 4 5 6

echo "Default mode: 2 + 2"
build-default/myCalc add 2 2
